version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pytest
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t mi-app .
  post_build:
    commands:
      - echo "Build completed successfully!"
