version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Iniciando las pruebas del código..."
      - pytest
  post_build:
    commands:
      - echo "¡Todo salió bien! Pruebas finalizadas."
